baseURL = "https://chikkirecipe.netlify.app"
languageCode = "en-us"
title = "Chikki Recipe"
theme = "z"

[taxonomies]
  tag = ""
  category = ""

[permalinks]
  post = ":slug"

[params]
  description = "The place for over 1000 popular recipes for your complete cooking guide"
  topdescription = "The place for over 1000 popular recipes for your complete cooking guide"
  toptitle = "Chikki Recipe"
  contentBackgroundColor = "#fff"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  contentTextColor = "#212529"
  cookieConsent = false
  customBlockquoteStyle = true
  customCodeStyle = true
  customDateFormat = "Jan 2, 2006"
  faviconMsApplicationTileColor = "#da532c"
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconThemeColor = "#ffffff"
  googleAnalytics = ""
  includeBootstrapJs = true
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  showPostSummary = false
  wrapperMaxWidth = ""
